services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ruang-edit-app
        working_dir: /var/www/html
        volumes:
            - ./app:/var/www/html
        depends_on:
            - mysql
        networks:
            - ruang-edit-net

    mysql:
        image: mysql:8.0
        container_name: ruang-edit-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ruang_edit
            MYSQL_USER: ilham
            MYSQL_PASSWORD: password
        volumes:
            - ruang-edit-mysql:/var/lib/mysql
        networks:
            - ruang-edit-net

    nginx:
        image: nginx:latest
        container_name: ruang-edit-nginx
        ports:
            - "8000:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html
        depends_on:
            - app
        networks:
            - ruang-edit-net

volumes:
    ruang-edit-mysql:

networks:
    ruang-edit-net:
